# Generated by Django 3.1.5 on 2021-09-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfacesModel',
            fields=[
                ('id', models.IntegerField(help_text='接口id', primary_key=True, serialize=False, verbose_name='接口id')),
                ('name', models.CharField(help_text='接口名称', max_length=50, verbose_name='接口名称')),
                ('tester', models.CharField(help_text='测试人员', max_length=20, verbose_name='测试人员')),
                ('desc', models.TextField(blank=True, help_text='接口描述', max_length=200, null=True, verbose_name='接口描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='更新时间')),
                ('project_id', models.ForeignKey(help_text='接口所属项目', on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel', verbose_name='接口所属项目')),
            ],
            options={
                'verbose_name': '接口表',
                'db_table': 'tb_interfaces',
                'ordering': ['id'],
            },
        ),
    ]
