# Generated by Django 3.1.5 on 2021-09-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interfacesmodel',
            old_name='project_id',
            new_name='project',
        ),
    ]
