# Generated by Django 3.1.5 on 2021-09-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.IntegerField(help_text='项目id', primary_key=True, serialize=False, verbose_name='项目id')),
                ('name', models.CharField(help_text='项目名称', max_length=50, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='项目名称', max_length=20, verbose_name='项目名称')),
                ('decs', models.TextField(blank=True, help_text='项目描述', max_length=200, null=True, verbose_name='项目描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目表',
                'db_table': 'tb_projects',
                'ordering': ['id'],
            },
        ),
    ]
