# Generated by Django 3.1.5 on 2021-09-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsmodel',
            old_name='decs',
            new_name='desc',
        ),
    ]
