# Generated by Django 3.1.5 on 2021-10-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210917_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='leader',
            field=models.CharField(help_text='项目负责人', max_length=20, verbose_name='项目负责人'),
        ),
    ]
